//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContact()
        {
            this.tblPersonalDetails = new HashSet<tblPersonalDetail>();
        }
    
        public int ID { get; set; }
        public string Town { get; set; }
        public string Ward { get; set; }
        public string LGA { get; set; }
        public string PartyAddress { get; set; }
        public string NextofKin { get; set; }
        public string kinAddress { get; set; }
        public string ContactNum1 { get; set; }
        public string KinContact { get; set; }
        public string ContactNum2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonalDetail> tblPersonalDetails { get; set; }
    }
}
