//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonalDetail
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Occupation { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> FingerID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblBusiness tblBusiness { get; set; }
        public virtual tblContact tblContact { get; set; }
        public virtual tblFingerprint tblFingerprint { get; set; }
    }
}
